version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: ketuai-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend/instance:/app/instance
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    container_name: ketuai-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80" 